[workspace]
members = [
    "example01-hello-world",
    "example02-primitives",
    "example03-custom-types",
    "example04-variable-bindings",
    "example05-types",
    "example06-conversion",
    "example07-expressions",
]

